name: TickSpeed
main: io.egg.tickspeed.TickSpeed
version: 1.0.2
author: EggAllocationService
api-version: "1.13" # this is here so legacy material support is not activated.
commands:
  tickspeed:
    description: Change or view the server tickspeed
    usage: /tickspeed [realtime|<tps>]